<?php

namespace AppBundle\Repository;

/**
 * OrdiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdiRepository extends \Doctrine\ORM\EntityRepository
{
}
